MARKET/a_shop/a_shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static





urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('inbox/',include('conversation.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MARKET/a_shop/conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'
urlpatterns = [
    path('', views.inbox, name = 'inbox'),
    path('<int:pk>/', views.detail_conversation, name='detail_conversation'),
    path('new/<int:item_pk>/', views.new_conversation, name = 'new_conversation'),
]

MARKET/a_shop/core/urls.py
from django.urls import path
from core import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm
app_name = 'core'

urlpatterns = [
    path('',views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="login.html", authentication_form=LoginForm), name='login'),
]

MARKET/a_shop/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', views.logout_site, name='logout_site')
]

MARKET/a_shop/item/urls.py
from django.urls import path
from . import views


app_name = 'item'

urlpatterns = [
    path('new/', views.new, name='new' ),
    path('', views.items, name='items' ),
    path('<int:pk>/', views.detail, name='detail' ),
    path('<int:pk>/delete/', views.delete, name='delete' ),
    path('<int:pk>/edit/', views.edit, name='edit' ),
]
 

MARKET/a_shop/dashboard/models.py
from django.db import models

# Create your models here.

MARKET/a_shop/item/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)
    
    class Meta:
        ordering = ("name",)
        verbose_name_plural = "Categories"
    def __str__(self):
        return self.name    
    
class Item(models.Model):
    category    = models.ForeignKey(Category, related_name = 'items', on_delete=models.CASCADE)
    name        = models.CharField(max_length=255)
    description = models.TextField(blank=True,null=True)
    price       = models.FloatField() 
    image       = models.ImageField(upload_to='item_images',blank=True,null=True)
    is_sold     = models.BooleanField(default=False)
    created_by  = models.ForeignKey(User, related_name = 'item', on_delete=models.CASCADE)
    created_at  = models.DateTimeField(auto_now_add=True)   
    
    def __str__(self):
        return self.name

MARKET/a_shop/item/forms.py
from django import forms
from .models import Item


INIPUT_CLASS = 'w-full py-4 px-6 rounded-xl border'
class NewItem(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category','name','description', 'price', 'image')

        widgets = {
            'category': forms.Select(attrs={
                'class': INIPUT_CLASS
            }),
            'name': forms.TextInput(attrs={
                'class': INIPUT_CLASS
            }),
            'description': forms.Textarea(attrs={
                'class': INIPUT_CLASS
            }),
            'price': forms.TextInput(attrs={
                'class': INIPUT_CLASS
            }),
            'image': forms.FileInput(attrs={
                'class': INIPUT_CLASS
            })
        }


class EditItem(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category','name','description', 'price', 'image', 'is_sold')

        widgets = {
            'category': forms.Select(attrs={
                'class': INIPUT_CLASS
            }),
            'name': forms.TextInput(attrs={
                'class': INIPUT_CLASS
            }),
            'description': forms.Textarea(attrs={
                'class': INIPUT_CLASS
            }),
            'price': forms.TextInput(attrs={
                'class': INIPUT_CLASS
            }),
            'image': forms.FileInput(attrs={
                'class': INIPUT_CLASS
            })
        }

MARKET/a_shop/dashboard/views.py
from django.shortcuts import render,get_object_or_404, redirect
from item.views import Item
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout


# Create your views here.

@login_required
def index(request):
    items = Item.objects.filter(created_by = request.user)
    
    return render(request, 'dashboard.html', {'items':items})

@login_required
def logout_site(request):
    logout(request)
    return redirect('/')

MARKET/a_shop/item/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Item,Category
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .forms import NewItem, EditItem
# Create your views here.

def items(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)
    
    if category_id:
        items = items.filter(category_id=category_id)
    
    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))
    
    return render(request, 'items.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id':int(category_id),
    })



def detail(request,pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold = False).exclude(pk=pk)[0:3]
    
    return render(request, 'detail.html',{'item':item, 'related_items':related_items})

@login_required
def new(request):
    if request.method == "POST":
        form = NewItem(request.POST, request.FILES)
        
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            
            return redirect('item:detail', pk=item.id)   
    else:
        form = NewItem() 
    return render(request, 'form.html', {'form':form, 'title':'New Item'})

@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by = request.user)
    item.delete()
    return redirect('dashboard:index')


@login_required
def edit(request, pk, ):
    item = get_object_or_404(Item, pk=pk, created_by = request.user)
    
    if request.method == "POST":
        form = EditItem(request.POST, request.FILES, instance=item)
        
        if form.is_valid():
            form.save()
            
            return redirect('item:detail', pk=item.id)   
    else:
        form = EditItem(instance=item) 
    return render(request, 'form.html', {'form':form, 'title':'Edit Item'})

MARKET/a_shop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>
        {% block title %}
            {% comment %} write title of the page..... {% endcomment %}
        {% endblock title %}
    </title>
</head>
<body>
    <div class="px-6 py-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">a_shop</a>

        <div class="space-x-6">
            <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">Add New Item</a>
            <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Search</a>
            {% if request.user.is_authenticated %}
                <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
                <a href="{% url 'dashboard:logout_site' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Logout</a>
            {% else %}
                <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Signup</a>
                <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a>
            {% endif %}

          
        </div>
    </div>
    <div class="px-6 py-6">
        {% block content %}
            {% comment %} write the content of the block.... {% endcomment %}
        {% endblock content %}
    </div>    
    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>
            <p class="text-lg text-gray-500">Hello, Django. I am from Bangladesh.I am from Bangladesh.I am from Bangladesh.I am from Bangladesh.I am from Bangladesh.</p>
        </div>
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>
            <ul class="space-y-2">
                {% comment %} <li><a href="{% url 'about' %}" class="text-lg text-teal-500 hover:text-teal-700">About</a></li> {% endcomment %}
                <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                {% comment %} <li><a href="{% url 'privacy_policy' %}" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a></li>
                <li><a href="{% url 'terms_of_use' %}" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li> {% endcomment %}
            </ul>
        </div>
    </footer>
</body>
</html>

MARKET/a_shop/templates/contact.html
{% extends "base.html" %}
{% block title %}contact{% endblock title %}


{% block content %}
    <h1>contact</h1>

{% endblock content %}

MARKET/a_shop/templates/dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock title %}


{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">My items</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{item.image.url}}" class="rounded-t-xl" alt="">
                        </div>
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-exl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock content %}

MARKET/a_shop/templates/detail.html
{% extends "base.html" %}
{% block title %}{{item.name}}{% endblock title %}


{% block content %}
    <div class="grid grid-cols-5 gap-6">
        <div class="col-span-3">
            <img src="{{item.image.url}}" class="rounded-t-xl">
        </div>
        <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
            <h1 class="mb-6 text-3xl">{{item.name}}</h1>
            <p class="text-gray-500"><strong>Price: </strong>{{item.price}}</p>
            <p class="text-gray-500"><strong>Seller: </strong>{{item.created_by.username}}</p>
            
            {% if item.description %}
                <p class="text-gray-700">
                    <strong class="text-gray=500">Description</strong><br>
                    {{ item.description}}
                </p>
            {% endif %}
            
            {% if request.user == item.created_by %}
            <div class="mt-6 p-6 bg-white rounded-xl">
                <p>This is your item!</p>
                <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 font-semibold bg-teal-600 text-white rounded-xl">
                    Edit
                </a>
                <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 font-semibold bg-red-600 text-white rounded-xl">
                    Delete
                </a>
            </div>
            {% else %}
                <a href="{% url 'conversation:new_conversation' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700"> Contact Seller</a>     
            {% endif %}

                
       
       
       
        </div>
    </div>
    {% if related_items %}
        <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
            <h2 class="mb-12 text-2xl text-center">Related items</h2>
            <div class="grid grid-cols-3 gap-3">
                {% for item in related_items %}
                    <div>
                        <a href="{% url 'item:detail' item.id %}">
                            <div>
                                <img src="{{item.image.url}}" class="rounded-t-xl" alt="">
                            </div>
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-exl">{{ item.name }}</h2>
                                <p class="text-gray-500">Price: {{ item.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
    
    
{% endblock content %}

MARKET/a_shop/templates/detail_conversation.html
{% extends "base.html" %}
{% block title %}Conversation{% endblock title %}
{% block content %}
    <h1 class="mb-6 text-3xl">Conversation</h1>
    <div class="space-y-6">
        {% for message in conversation.messages.all %}
            
        <div class="p-4 flex flex-col {% if message.created_by == request.user %}bg-blue-100 text-right{% else %}bg-gray-100{% endif %} rounded-xl">
                <p class="mb-4 "><strong>{{ message.created_by.username}}</strong>@{{ message.created_at }}</p>
                <p>{{message.content}}</p>
            </div>           
        
        {% endfor %}
    </div>
    <form action="." method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <button class="py-2 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white font-semibold">Send</button>

    </form>
{% endblock content %}

MARKET/a_shop/templates/form.html
{% extends "base.html" %}
{% block title %}{{title}}{% endblock title %}

{% block content %}

<h1 class="mb-6 text-3xl">
    {{title}}
</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{form.as_p}}
    </div>
    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{field.errors}}
            {% endfor %}
            {{ form.non_field_errors }}

        </div>

    {% endif %}
    <button class="py-2 px-8 mt-6 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white font-semibold">Submit</button>

</form>
{% endblock content %}

MARKET/a_shop/templates/inbox.html
{% extends "base.html" %}
{% block title %}Inbox{% endblock title %}
{% block content %}
    <h1 class="mb-6 text-3xl">Inbox</h1>
    <div class="space-y-6">
        {% for conversation in conversations %}
            <a href="{% url 'conversation:detail_conversation' conversation.id %}">
                <div class="p-6 flex bg-gray-100 rounded-xl">
                    <div class="pr-6">
                        <img src="{{ conversation.item.image.url }}" class="w-20 rounded-xl">
                    </div>
                    <div>
                        {% for member in  conversation.members.all %}
                            {% if member != request.user %}
                                <p class="mb-4"><strong>{{member.username}}</strong> | {{conversation.modified_at}} </p>
                                <p>{{ conversation.item.name}}</p>

                            {% endif %}
                        
                        {% endfor %}
                    </div>
                </div>
            </a>
        
        {% endfor %}
    </div>
{% endblock content %}

MARKET/a_shop/templates/index.html
{% extends "base.html" %}
{% block title %}index{% endblock title %}


{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest items</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{item.image.url}}" class="rounded-t-xl" alt="">
                        </div>
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-exl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>
        <div class="grid grid-cols-3 gap-3 mt-6">
            {% for category in categories %}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-xl">
                            <h2 class="text-exl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{category.items.count}} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock content %}

MARKET/a_shop/templates/items.html
{% extends "base.html" %}
{% block title %}Items{% endblock title %}


{% block content %}
    <div class="pb-6 grid pt-6 grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1">
            <form method="get" action="{% url 'item:items' %}">
                <input type="text" name="query" class="w-full py-4 px-6 border rounded-xl" value="{{ query }}" placeholder="Search for items">
                <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl"> Search</button>
            </form>
            <hr class="my-6">
            <p class="font-semibold">Categories</p>
            <ul>
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl {% if category.id == category_id %} bg-gray-200 {% endif %}">
                        <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>

            <hr class="my-6">
            <p class="font-semibold">Clear Filters</p>
            <ul>
                <li><a href="{% url 'item:items' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a></li>
            </ul>

        </div>

        <div class="col-span-3">
            <div class="grid grid-cols-3 gap-3">
                {% for item in items %}
                    <div>
                        <a href="{% url 'item:detail' item.id %}">
                            <div>
                                <img src="{{item.image.url}}" class="rounded-t-xl" alt="">
                            </div>
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-exl">{{ item.name }}</h2>
                                <p class="text-gray-500">Price: {{ item.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock content %}

MARKET/a_shop/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock title %}

{% block content %}

    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Login</h1>
        <form method="post" action=".">{% csrf_token %}
            <div class="mb-3">
                <label for="username" class="inline-block mb-2">Username:</label><br>
                {{form.username}}
            </div>
            <div class="mb-3">
                <label for="password" class="inline-block mb-2">Password:</label><br>
                {{form.password}}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{field.errors}}
                    {% endfor %}
                    {{ form.non_field_errors }}

                </div>

            {% endif %}
            <button class="py-2 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white font-semibold">Submit</button>

        </form>
    </div>

{% endblock content %}

MARKET/a_shop/templates/new.html
{% extends "base.html" %}
{% block title %}New Conversation{% endblock title %}

{% block content %}
    <h1 class="mb-6 text-3xl">New Conversation</h1>
    <form method="post" action=".">
        {% csrf_token %}
    
        <div class="space-y-4">
            {{form.as_p}}
        </div>
        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{field.errors}}
                {% endfor %}
                {{ form.non_field_errors }}
    
            </div>
    
        {% endif %}
        <button class="py-2 px-8 mt-6 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white font-semibold">Send</button>
    
    </form>

{% endblock content %}

MARKET/a_shop/templates/signup.html
{% extends "base.html" %}
{% block title %}Signup{% endblock title %}

{% block content %}

    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Signup</h1>
        <form method="post" action=".">{% csrf_token %}
            <div class="mb-3">
                <label for="username" class="inline-block mb-2">Username:</label><br>
                {{form.username}}
            </div>
            <div class="mb-3">
                <label for="email" class="inline-block mb-2">Email:</label><br>
                {{form.email}}
            </div>
            <div class="mb-3">
                <label for="password" class="inline-block mb-2">Password:</label><br>
                {{form.password1}}
            </div>
            <div class="mb-3">
                <label for="repeat_password" class="inline-block mb-2">Repeat Password:</label><br>
                {{form.password2}}
            </div>
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{field.errors}}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>

            {% endif %}
            <button class="py-2 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white font-semibold">Submit</button>

        </form>
    </div>

{% endblock content %}